export interface Product {
  id: string;
  name: string;
  category: string;
  description: string;
  features: string[];
  image: string;
}

export const products: Product[] = [
  {
    id: 'chain-pulley-block',
    name: 'Chain Pulley Block',
    category: 'Hoists & Lifts',
    description: 'Lightweight and durable chain pulley blocks for manual lifting operations. Ideal for workshops, warehouses, and construction sites.',
    features: ['Durable construction', 'Load capacity up to 20 tons', 'Smooth operation', 'Easy maintenance'],
    image: '/products/chain-pulley-block.jpg',
  },
  {
    id: 'electric-mini-hoist',
    name: 'Electric Mini Hoist',
    category: 'Hoists & Lifts',
    description: 'Compact electric hoisting solution for precise lifting and positioning tasks in confined spaces.',
    features: ['Compact design', 'Variable speed control', 'Energy efficient', 'Lightweight'],
    image: '/products/electric-hoist.jpg',
  },
  {
    id: 'electric-chain-hoist',
    name: 'Electric Chain Hoist',
    category: 'Hoists & Lifts',
    description: 'Powerful electric chain hoists for heavy-duty lifting in industrial environments.',
    features: ['High load capacity', 'Reliable operation', 'Advanced safety features', 'Low maintenance'],
    image: '/products/electric-hoist.jpg',
  },
  {
    id: 'ratchet-lever-hoist',
    name: 'Ratchet Lever Hoist',
    category: 'Hoists & Lifts',
    description: 'Manual ratchet lever hoists for secure and controlled lifting operations.',
    features: ['Simple operation', 'Load holding capability', 'Portable design', 'Compact size'],
    image: '/products/chain-pulley-block.jpg',
  },
  {
    id: 'electric-wire-rope-hoist',
    name: 'Electric Wire Rope Hoist',
    category: 'Hoists & Lifts',
    description: 'Heavy-duty wire rope hoists for large-scale industrial lifting applications.',
    features: ['High capacity', 'Durability', 'Precision control', 'Safety brakes'],
    image: '/products/electric-hoist.jpg',
  },
  {
    id: 'geared-trolley',
    name: 'Geared Trolley',
    category: 'Trolleys & Carriers',
    description: 'Efficient trolleys for smooth material transport and positioning on overhead cranes.',
    features: ['Smooth rolling', 'Load distribution', 'Adjustable width', 'Durable wheels'],
    image: '/products/hand-trolley.jpg',
  },
  {
    id: 'electric-winch-machine',
    name: 'Electric Winch Machine',
    category: 'Winches',
    description: 'Powerful electric winch machines for heavy pulling and lifting operations.',
    features: ['High pulling force', 'Variable speed', 'Rope capacity options', 'Thermal protection'],
    image: '/products/winch-machine.jpg',
  },
  {
    id: 'thruster-brake',
    name: 'Thruster Brake',
    category: 'Brakes & Safety',
    description: 'Advanced braking systems ensuring safe load holding and controlled descent.',
    features: ['Fail-safe design', 'Smooth braking', 'Long service life', 'Reliable operation'],
    image: '/products/electric-hoist.jpg',
  },
  {
    id: 'construction-winch',
    name: 'Construction Winch Machine',
    category: 'Winches',
    description: 'Specialized winch machines for construction sites and building projects.',
    features: ['Portable design', 'Durable construction', 'Easy installation', 'Weather resistant'],
    image: '/products/winch-machine.jpg',
  },
  {
    id: 'monkey-crane-winch',
    name: 'Monkey Crane Winch',
    category: 'Winches',
    description: 'Versatile winch solution for flexible material handling and positioning tasks.',
    features: ['Flexible mounting', 'Compact size', 'Multiple configurations', 'Easy operation'],
    image: '/products/winch-machine.jpg',
  },
  {
    id: 'pulling-lifting-machine',
    name: 'Pulling & Lifting Machine',
    category: 'Hoists & Lifts',
    description: 'Multipurpose machines for both horizontal pulling and vertical lifting operations.',
    features: ['Dual functionality', 'Power adjustment', 'Safety features', 'Portable'],
    image: '/products/electric-hoist.jpg',
  },
  {
    id: 'cable-puller',
    name: 'Cable Puller',
    category: 'Cable Equipment',
    description: 'Specialized equipment for cable installation and management in electrical and telecom applications.',
    features: ['Precision control', 'Adjustable force', 'Portable design', 'Easy setup'],
    image: '/products/wire-rope.jpg',
  },
  {
    id: 'wire-rope',
    name: 'Wire Rope',
    category: 'Ropes & Slings',
    description: 'High-strength steel wire ropes for lifting, rigging, and suspension applications.',
    features: ['High tensile strength', 'Corrosion resistant', 'Various diameters', 'Certified quality'],
    image: '/products/wire-rope.jpg',
  },
  {
    id: 'pvc-coated-wire-rope',
    name: 'PVC Coated Wire Rope',
    category: 'Ropes & Slings',
    description: 'Wire ropes with protective PVC coating for enhanced durability and weather resistance.',
    features: ['Weather resistant', 'Extended life', 'Smooth surface', 'Color coded options'],
    image: '/products/wire-rope.jpg',
  },
  {
    id: 'wire-rope-slings',
    name: 'Wire Rope Slings',
    category: 'Ropes & Slings',
    description: 'Pre-manufactured wire rope slings for safe and efficient load lifting.',
    features: ['Certified safe', 'Eye terminations', 'Various configurations', 'Load rated'],
    image: '/products/wire-rope.jpg',
  },
  {
    id: '4-legged-wire-rope-slings',
    name: '4 Legged Wire Rope Slings',
    category: 'Ropes & Slings',
    description: 'Heavy-duty four-legged slings for balanced load distribution and stable lifting.',
    features: ['Balanced lifting', 'Load spreading', 'Protective sleeves', 'Certified construction'],
    image: '/products/wire-rope.jpg',
  },
  {
    id: '4-legged-chain-slings',
    name: '4 Legged Chain Slings',
    category: 'Ropes & Slings',
    description: 'Industrial-grade chain slings with four legs for heavy load handling.',
    features: ['Heavy duty', 'Flexible rigging', 'Heat resistant', 'Certified safe'],
    image: '/products/chain-pulley-block.jpg',
  },
  {
    id: 'wr-clamps',
    name: 'W.R. Clamps',
    category: 'Clamps & Hardware',
    description: 'Wire rope clamps for secure rope terminations and adjustments.',
    features: ['Secure grip', 'Easy installation', 'Multiple sizes', 'High quality steel'],
    image: '/products/wire-rope.jpg',
  },
  {
    id: 'braided-rope',
    name: 'Braided Rope',
    category: 'Ropes & Slings',
    description: 'High-strength braided ropes for general industrial applications and rigging.',
    features: ['Flexible', 'Durable', 'UV resistant', 'Multiple diameters'],
    image: '/products/wire-rope.jpg',
  },
  {
    id: 'pp-ropes',
    name: 'P.P. Ropes',
    category: 'Ropes & Slings',
    description: 'Lightweight polypropylene ropes for various industrial and commercial uses.',
    features: ['Lightweight', 'Corrosion resistant', 'Cost effective', 'Flexible'],
    image: '/products/wire-rope.jpg',
  },
  {
    id: 'wall-winch-machine',
    name: 'Wall Winch Machine',
    category: 'Winches',
    description: 'Space-saving wall-mounted winch systems for warehouses and workshops.',
    features: ['Wall mount design', 'Space efficient', 'Easy access', 'Durable construction'],
    image: '/products/winch-machine.jpg',
  },
  {
    id: 'bitumen-compound',
    name: 'Bitumen Compound',
    category: 'Maintenance & Supplies',
    description: 'Protective bitumen compounds for wire rope and equipment preservation.',
    features: ['Corrosion protection', 'Weather resistant', 'Easy application', 'Cost effective'],
    image: '/products/wire-rope.jpg',
  },
  {
    id: 'crane-scale',
    name: 'Crane Scale',
    category: 'Measuring Equipment',
    description: 'Precision digital scales for accurate load monitoring during lifting operations.',
    features: ['Digital display', 'High accuracy', 'Reliable readings', 'Durable design'],
    image: '/products/electric-hoist.jpg',
  },
  {
    id: 'dee-shackle',
    name: 'Dee Shackle',
    category: 'Hardware & Fittings',
    description: 'Heavy-duty D-shaped shackles for lifting and rigging applications.',
    features: ['Strong construction', 'Easy connection', 'Multiple sizes', 'High quality steel'],
    image: '/products/chain-pulley-block.jpg',
  },
  {
    id: 'bow-shackle',
    name: 'Bow Shackle',
    category: 'Hardware & Fittings',
    description: 'Bow-shaped shackles providing effective load connection for rigging operations.',
    features: ['High load capacity', 'Durable design', 'Easy pin removal', 'Certified safe'],
    image: '/products/chain-pulley-block.jpg',
  },
  {
    id: 'connecting-link',
    name: 'Connecting Link',
    category: 'Hardware & Fittings',
    description: 'Chain connecting links for quick and secure chain assembly.',
    features: ['Quick connect', 'Strong joints', 'Easy replacement', 'Reliable operation'],
    image: '/products/chain-pulley-block.jpg',
  },
  {
    id: 'hand-pallet-truck',
    name: 'Hand Pallet Truck',
    category: 'Material Handling',
    description: 'Hydraulic hand pallet trucks for efficient warehouse material movement.',
    features: ['Hydraulic lift', 'Easy operation', 'Load capacity up to 3 tons', 'Durable wheels'],
    image: '/products/hand-trolley.jpg',
  },
  {
    id: 'hand-stacker',
    name: 'Hand Stacker',
    category: 'Material Handling',
    description: 'Manual hand stackers for lifting and stacking materials in warehouses.',
    features: ['Manual operation', 'Compact design', 'Stackable materials', 'Easy maneuverability'],
    image: '/products/hand-trolley.jpg',
  },
  {
    id: 'scissor-table',
    name: 'Scissor Table',
    category: 'Material Handling',
    description: 'Hydraulic scissor lift tables for safe material loading and unloading.',
    features: ['Hydraulic system', 'Smooth operation', 'Safety features', 'Stable platform'],
    image: '/products/hand-trolley.jpg',
  },
  {
    id: 'hand-trolley',
    name: 'Hand Trolley',
    category: 'Material Handling',
    description: 'Sturdy hand trolleys for moving heavy items in warehouses and shops.',
    features: ['Robust design', 'Easy to maneuver', 'Large wheels', 'Multiple handle positions'],
    image: '/products/hand-trolley.jpg',
  },
  {
    id: 'web-sling',
    name: 'Web Sling',
    category: 'Ropes & Slings',
    description: 'Synthetic web slings for safe and gentle handling of delicate loads.',
    features: ['Gentle grip', 'Load rated', 'Color coded', 'Weather resistant'],
    image: '/products/wire-rope.jpg',
  },
  {
    id: 'round-slings',
    name: 'Round Slings',
    category: 'Ropes & Slings',
    description: 'Protective round slings for load distribution and equipment safety.',
    features: ['Load spreading', 'Equipment protection', 'Flexible design', 'Durable construction'],
    image: '/products/wire-rope.jpg',
  },
  {
    id: 'ratchet-lashing-belt',
    name: 'Ratchet Lashing Belt',
    category: 'Safety & Securing',
    description: 'Ratchet-operated lashing belts for secure cargo securing in transport.',
    features: ['Secure locking', 'Adjustable length', 'Easy operation', 'Durable straps'],
    image: '/products/safety-equipment.jpg',
  },
  {
    id: 'safety-belt',
    name: 'Safety Belt',
    category: 'Safety Equipment',
    description: 'Professional safety harnesses and belts for working at heights.',
    features: ['Certified safe', 'Comfortable wear', 'Adjustment options', 'Durable materials'],
    image: '/products/safety-equipment.jpg',
  },
  {
    id: 'safety-shoe',
    name: 'Safety Shoe',
    category: 'Safety Equipment',
    description: 'Industrial safety footwear with steel toe protection and slip resistance.',
    features: ['Steel toe', 'Slip resistant', 'Comfortable', 'Durable sole'],
    image: '/products/safety-equipment.jpg',
  },
  {
    id: 'safety-jackets',
    name: 'Safety Jackets',
    category: 'Safety Equipment',
    description: 'High-visibility safety jackets for worker protection on job sites.',
    features: ['High visibility', 'Reflective strips', 'Multiple pockets', 'Comfortable fit'],
    image: '/products/safety-equipment.jpg',
  },
  {
    id: 'wheel-barrow',
    name: 'Wheel Barrow',
    category: 'Material Handling',
    description: 'Sturdy wheelbarrows for material transport in construction and gardening.',
    features: ['Stable design', 'Large capacity', 'Easy maneuverability', 'Durable construction'],
    image: '/products/hand-trolley.jpg',
  },
  {
    id: 'hand-gloves',
    name: 'Hand Gloves',
    category: 'Safety Equipment',
    description: 'Protective work gloves for safe handling of sharp and rough materials.',
    features: ['Hand protection', 'Grip enhancement', 'Durable material', 'Various sizes'],
    image: '/products/safety-equipment.jpg',
  },
  {
    id: 'turn-buckles',
    name: 'Turn Buckles',
    category: 'Hardware & Fittings',
    description: 'Adjustable turn buckles for tension control in rigging and securing applications.',
    features: ['Adjustable length', 'Secure locking', 'Easy operation', 'High quality construction'],
    image: '/products/chain-pulley-block.jpg',
  },
  {
    id: 'eye-hook',
    name: 'Eye Hook',
    category: 'Hardware & Fittings',
    description: 'Heavy-duty eye hooks for lifting and rigging point attachment.',
    features: ['Strong eye', 'Load rated', 'Easy screw-in', 'Various sizes'],
    image: '/products/chain-pulley-block.jpg',
  },
  {
    id: 'plate-lifting-clamps-v',
    name: 'Plate Lifting Clamps (V)',
    category: 'Clamps & Hardware',
    description: 'Vertical plate lifting clamps for safe handling of steel plates and flat materials.',
    features: ['Secure grip', 'Load rated', 'Vertical orientation', 'Easy operation'],
    image: '/products/chain-pulley-block.jpg',
  },
  {
    id: 'plate-lifting-clamps-h',
    name: 'Plate Lifting Clamps (H)',
    category: 'Clamps & Hardware',
    description: 'Horizontal plate lifting clamps for versatile plate handling applications.',
    features: ['Horizontal grip', 'Adjustable width', 'Load safety', 'Durable construction'],
    image: '/products/chain-pulley-block.jpg',
  },
  {
    id: 'swivel-eye-hook',
    name: 'Swivel Eye Hook',
    category: 'Hardware & Fittings',
    description: 'Rotating eye hooks for flexible lifting and rigging without twisting.',
    features: ['360° rotation', 'Load rated', 'Smooth movement', 'Durable construction'],
    image: '/products/chain-pulley-block.jpg',
  },
  {
    id: 'beam-clamps',
    name: 'Beam Clamps',
    category: 'Clamps & Hardware',
    description: 'Universal beam clamps for secure attachment to structural beams.',
    features: ['Flexible mounting', 'Load rated', 'Easy installation', 'Multiple sizes'],
    image: '/products/chain-pulley-block.jpg',
  },
  {
    id: 'cable-trolley',
    name: 'Cable Trolley',
    category: 'Trolleys & Carriers',
    description: 'Specialized trolleys for cable management and material transport.',
    features: ['Smooth operation', 'Wire management', 'Mobile design', 'Durable wheels'],
    image: '/products/hand-trolley.jpg',
  },
  {
    id: 'cable-carrier',
    name: 'Cable Carrier',
    category: 'Cable Equipment',
    description: 'Cable carriers for organized electrical wiring in industrial installations.',
    features: ['Organization', 'Protection', 'Easy access', 'Modular design'],
    image: '/products/wire-rope.jpg',
  },
  {
    id: 'busbar',
    name: 'Busbar',
    category: 'Electrical Equipment',
    description: 'Electrical busbars for power distribution in industrial applications.',
    features: ['Efficient conduction', 'Heat dissipation', 'Multiple configurations', 'Quality copper'],
    image: '/products/wire-rope.jpg',
  },
  {
    id: 'pendant-station-remote',
    name: 'Pendant Station Remote',
    category: 'Control Equipment',
    description: 'Wireless control systems for remote operation of lifting equipment.',
    features: ['Wireless control', 'Long range', 'Safety features', 'Easy operation'],
    image: '/products/electric-hoist.jpg',
  },
  {
    id: 'cable-drum-jacks',
    name: 'Cable Drum Jacks',
    category: 'Jacks & Supports',
    description: 'Jacks for supporting and positioning cable drums during installation.',
    features: ['Stable support', 'Adjustable height', 'Easy setup', 'Load capacity'],
    image: '/products/hand-trolley.jpg',
  },
  {
    id: 'eye-bolt',
    name: 'Eye Bolt',
    category: 'Hardware & Fittings',
    description: 'Precision eye bolts for secure lifting point attachment.',
    features: ['Precision threads', 'Load rated', 'Multiple sizes', 'High quality steel'],
    image: '/products/chain-pulley-block.jpg',
  },
  {
    id: 'master-link-assembly',
    name: 'Master Link Assembly',
    category: 'Hardware & Fittings',
    description: 'Chain master links for quick and secure chain connections.',
    features: ['Quick connect', 'Strong joint', 'Easy assembly', 'Certified safety'],
    image: '/products/chain-pulley-block.jpg',
  },
  {
    id: 'cable-roller',
    name: 'Cable Roller',
    category: 'Rollers & Wheels',
    description: 'Specialized rollers for cable routing and management in installations.',
    features: ['Smooth rolling', 'Cable protection', 'Adjustable angle', 'Durable construction'],
    image: '/products/wire-rope.jpg',
  },
  {
    id: 'scaffolding-beam-brackets',
    name: 'Scaffolding Beam Brackets',
    category: 'Scaffolding',
    description: 'Structural brackets for secure scaffolding and support assembly.',
    features: ['Load rated', 'Easy assembly', 'Durable steel', 'Multiple configurations'],
    image: '/products/chain-pulley-block.jpg',
  },
  {
    id: 'pipe-clamps',
    name: 'Pipe Clamps',
    category: 'Clamps & Hardware',
    description: 'Adjustable clamps for securing pipes and tubes in industrial setups.',
    features: ['Adjustable width', 'Secure grip', 'Easy fastening', 'Durable design'],
    image: '/products/chain-pulley-block.jpg',
  },
  {
    id: 'cup-lock-system',
    name: 'Cup Lock System',
    category: 'Scaffolding',
    description: 'Quick-lock scaffolding system for rapid assembly and dismantling.',
    features: ['Quick assembly', 'Secure locking', 'Flexible configuration', 'Reusable components'],
    image: '/products/chain-pulley-block.jpg',
  },
  {
    id: 'divider-cone',
    name: 'Divider Cone',
    category: 'Safety & Traffic',
    description: 'Traffic safety cones for site marking and hazard indication.',
    features: ['High visibility', 'Durable material', 'Weather resistant', 'Portable design'],
    image: '/products/safety-equipment.jpg',
  },
  {
    id: 'road-safety-fence-barricade',
    name: 'Road Safety Fence Barricade',
    category: 'Safety & Traffic',
    description: 'Temporary fencing and barricades for site safety and access control.',
    features: ['Safety marking', 'Easy setup', 'Durable construction', 'Portable design'],
    image: '/products/safety-equipment.jpg',
  },
  {
    id: 'tree-cutting-tools',
    name: 'Tree Cutting Tools',
    category: 'Tools',
    description: 'Professional tree cutting equipment for forestry and maintenance applications.',
    features: ['Precision cutting', 'Power efficiency', 'Safety features', 'Durability'],
    image: '/products/hand-trolley.jpg',
  },
  {
    id: 'power-tools',
    name: 'Power Tools',
    category: 'Tools',
    description: 'Industrial-grade power tools for construction and manufacturing applications.',
    features: ['High performance', 'Durable construction', 'Multiple functionalities', 'Safety certified'],
    image: '/products/hand-trolley.jpg',
  },
];
